parameters:
    'salesforce_api.password': '%env(SALESFORCE_PASSWORD)%'
    'salesforce_api.token': '%env(SALESFORCE_TOKEN)%'
    'salesforce_api.username': '%env(SALESFORCE_USERNAME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    jalismrs_salesforce_api.salesforce_api:
        class: 'Jalismrs\Symfony\Bundle\JalismrsSalesforceApiBundle\SalesforceApi'
        arguments:
            $apiThrottler: '@Jalismrs\Symfony\Bundle\JalismrsApiThrottlerBundle\ApiThrottler'
            $sforceEnterpriseClient: '@SforceEnterpriseClient'
            $username: '%jalismrs_salesforce_api.username%'
            $password: '%@jalismrs_salesforce_api.password%'
            $token: '%@jalismrs_salesforce_api.token%'
    
    Jalismrs\Symfony\Bundle\JalismrsSalesforceApiBundle\SalesforceApi: '@jalismrs_salesforce_api.salesforce_api'
    
    # developerforce/force.com-toolkit-for-php
    SforceEnterpriseClient:
        class: 'SforceEnterpriseClient'
