services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # aliases
    Jalismrs\Symfony\Bundle\JalismrsSalesforceApiBundle\SalesforceApi: '@jalismrs_salesforce_api.salesforce_api'

    # services
    jalismrs_salesforce_api.salesforce_api:
        arguments:
            $apiThrottler: '@Jalismrs\Symfony\Bundle\JalismrsApiThrottlerBundle\ApiThrottler'
            $sforceEnterpriseClient: '@jalismrs_salesforce_api.dependency.developerforce.force_com_toolkit_for_php.sforce_enterprise_client'
        class: 'Jalismrs\Symfony\Bundle\JalismrsSalesforceApiBundle\SalesforceApi'
    
    # DEPENDENCIES -------------------------------------------------------------
    # developerforce/force.com-toolkit-for-php
    jalismrs_salesforce_api.dependency.developerforce.force_com_toolkit_for_php.sforce_enterprise_client:
        class: 'SforceEnterpriseClient'
