parameters:
    'salesforce.password': '%env(SALESFORCE_PASSWORD)%'
    'salesforce.token': '%env(SALESFORCE_TOKEN)%'
    'salesforce.username': '%env(SALESFORCE_USERNAME)%'

services:
    _defaults:
        public: false
    
    salesforce_api.salesforce_api:
        class: 'Jalismrs\SalesforceApiBundle\SalesforceApi'
        arguments:
            $apiThrottler: '@Jalismrs\ApiThrottlerBundle\ApiThrottler'
            $sforceEnterpriseClient: '@SforceEnterpriseClient'
    
    Jalismrs\SalesforceApiBundle\SalesforceApi: '@salesforce_api.salesforce_api'
    
    # developerforce/force.com-toolkit-for-php
    SforceEnterpriseClient:
        calls:
            - createConnection:
                $wsdl: '../../../salesforce.wsdl.xml'
            - login:
                $username: '%env(SALESFORCE_USERNAME)%'
                $password: '%env(SALESFORCE_PASSWORD)%%env(SALESFORCE_TOKEN)%
        class: 'SforceEnterpriseClient'
