services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    # aliases
    Jalismrs\Symfony\Bundle\JalismrsSalesforceApiBundle\SalesforceApi: '@jalismrs_salesforce_api.salesforce_api'

    # services
    jalismrs_salesforce_api.salesforce_api:
        class: 'Jalismrs\Symfony\Bundle\JalismrsSalesforceApiBundle\SalesforceApi'
        arguments:
            $apiThrottler: '@Jalismrs\Symfony\Bundle\JalismrsApiThrottlerBundle\ApiThrottler'
            $sforceEnterpriseClient: '@SforceEnterpriseClient'
            $username: '%jalismrs_salesforce_api.username%'
            $password: '%@jalismrs_salesforce_api.password%'
            $token: '%@jalismrs_salesforce_api.token%'
    
    # DEPENDENCIES -------------------------------------------------------------
    # developerforce/force.com-toolkit-for-php
    SforceEnterpriseClient:
        class: 'SforceEnterpriseClient'
